name: build

on:
  push:
    branches:
      - master
      - node18
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README
        run: node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPOTIFY_UID: ${{ secrets.SPOTIFY_UID }}
          GHOST_HUNTER_SCORES: ${{ secrets.GHOST_HUNTER_SCORES }}
          JET_DASH_VR_SCORES: ${{ secrets.JET_DASH_VR_SCORES }}
      - name: Commit README
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}